version: 2

project_name: gclone

before:
  hooks:
    - go test ./...

builds:
  - main: .
    binary: gclone
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
      - -buildvcs=false
      - -buildinfo=false
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - 386
    ignore:
      - goos: darwin
        goarch: 386
    ldflags:
      - -s -w -buildid=

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}

checksum:
  name_template: checksums.txt

changelog:
  use: github
