---
name: ci

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - "**.md"
      - "docs/**"
  pull_request:
    branches:
      - main
      - master
    paths-ignore:
      - "**.md"
      - "docs/**"

jobs:
  test:
    name: Test & Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          cache: true

      - name: Set up UPX
        uses: crazy-max/ghaction-upx@v4
        with:
          install-only: true

      - name: Run tests
        run: go test -v ./...

      - name: Check GoReleaser Config
        uses: goreleaser/goreleaser-action@v7
        with:
          distribution: goreleaser
          version: latest
          args: check
